CREATE TYPE USER_ROLE AS ENUM ('USER', 'ADMIN', 'SUPER_ADMIN');

UPDATE users
SET role = 'USER'::USER_ROLE
WHERE role = 'user';

UPDATE users
SET role = 'ADMIN'::USER_ROLE
WHERE role = 'admin';

ALTER TABLE users
    ALTER COLUMN role DROP DEFAULT,
    ALTER COLUMN role TYPE USER_ROLE USING role::text::USER_ROLE,
    ALTER COLUMN role SET DEFAULT 'USER'::USER_ROLE;

ALTER TYPE gender ADD VALUE 'DIFFERENT';
