CREATE TYPE GENDER AS ENUM ('MALE', 'FEMALE', 'NONE_OF_YOUR_BUSINESS');
ALTER TABLE customer
ADD gender GENDER;
UPDATE customer SET gender = 'NONE_OF_YOUR_BUSINESS'
WHERE gender IS NULL;
ALTER TABLE customer
ALTER COLUMN gender SET NOT NULL;