CREATE TABLE brand(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    foundation_date TIMESTAMP NOT NULL,
    country_of_origin VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    history VARCHAR(255) NOT NULL,
    date_added TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);