services:

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: mzamota
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped

  spring-sandbox-api:
    container_name: spring-sandbox-api
    image: acidcommunism69/spring-sandbox-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8081:3001"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  spring-sandbox-react-ui:
    container_name: spring-sandbox-react-ui
    image: acidcommunism69/spring-sandbox-react-ui
    build:
      context: frontend/react
      args:
        spring_sandbox_api_base_url: http://localhost:8081
    ports:
      - "3000:5173"
    depends_on:
      - spring-sandbox-api
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db: