server:
  port: 3001
  error:
    include-message: always
  http2:
    enabled: true

cors:
  allowedOrigins: "*"
  allowedMethods: "*"

logging:
  level:
    org.springframework.security: TRACE

spring:
#  security:
#    user:
#      name: max
#      password: asdg34rbnlok
  mvc:
    dispatch-trace-request: true
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: mzamota
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  flyway:
    baseline-on-migrate: true
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      group:
        custom:
          show-components: "always"
          show-details: "always"
