name: CD - deploy backend

on:
  push:
    branches:
      - master
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: ${{ secrets.PG_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: customer
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and run unit+integration tests
        run: ./gradlew --stacktrace build -DdockerImageTag=${{ steps.build-number.outputs.BUILD_NUMBER }}

      - name: Upload new docker image
        run: ./gradlew --no-daemon --stacktrace jib -DdockerImageTag=${{ steps.build-number.outputs.BUILD_NUMBER }}

      - name: Update Dockerrun.aws.json image tag with new build number
        run: |
          echo "./infrastructure/Dockerrun.aws.json before updating tag"
          cat ./infrastructure/Dockerrun.aws.json
          sed -i -E 's_(acidcommunism69/spring-sandbox-api:)([^"]*)_\1'${{ steps.build-number.outputs.BUILD_NUMBER }}'_' Dockerrun.aws.json
          echo "./infrastructure/Dockerrun.aws.json after updating tag"
          cat ./infrastructure/Dockerrun.aws.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.sha }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: infrastructure/Dockerrun.aws.json

      - name: Commit and push Dockerrun.aws.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerrun.aws.json docker image with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push