name: CI - Build Backend

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.PG_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: customer
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and run unit+integration tests
        run: ./gradlew build --stacktrace

      - name: Send telegram notification
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TELEGRAM_CHAT_ID }} # user id or channel name secret
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }} # token secret
          status: ${{ job.status }} # do not modify this line